/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package datahub;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DHType implements org.apache.thrift.TEnum {
  Boolean(0),
  Integer(1),
  Double(2),
  Text(3),
  Binary(4),
  Date(5),
  DateTime(6),
  TimeStamp(7);

  private final int value;

  private DHType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DHType findByValue(int value) { 
    switch (value) {
      case 0:
        return Boolean;
      case 1:
        return Integer;
      case 2:
        return Double;
      case 3:
        return Text;
      case 4:
        return Binary;
      case 5:
        return Date;
      case 6:
        return DateTime;
      case 7:
        return TimeStamp;
      default:
        return null;
    }
  }
}
