/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface datahub_accountAccountException : NSException <TBase, NSCoding> {
  int32_t __error_code;
  NSString * __message;
  NSString * __details;

  BOOL __error_code_isset;
  BOOL __message_isset;
  BOOL __details_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=error_code, setter=setError_code:) int32_t error_code;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=details, setter=setDetails:) NSString * details;
#endif

- (id) init;
- (id) initWithError_code: (int32_t) error_code message: (NSString *) message details: (NSString *) details;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) error_code;
- (void) setError_code: (int32_t) error_code;
#endif
- (BOOL) error_codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) details;
- (void) setDetails: (NSString *) details;
#endif
- (BOOL) detailsIsSet;

@end

@protocol datahub_accountAccountService <NSObject>
- (double) get_version;  // throws TException
- (BOOL) create_account: (NSString *) username email: (NSString *) email password: (NSString *) password repo_name: (NSString *) repo_name app_id: (NSString *) app_id app_token: (NSString *) app_token;  // throws datahub_accountAccountException *, TException
- (BOOL) remove_account: (NSString *) username app_id: (NSString *) app_id app_token: (NSString *) app_token;  // throws datahub_accountAccountException *, TException
@end

@interface datahub_accountAccountServiceClient : NSObject <datahub_accountAccountService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface datahub_accountAccountServiceProcessor : NSObject <TProcessor> {
  id <datahub_accountAccountService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAccountService: (id <datahub_accountAccountService>) service;
- (id<datahub_accountAccountService>) service;
@end

@interface datahub_accountaccountConstants : NSObject {
}
@end
